language: c
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: bionic

env:
  global:
    - secure: "your_coverity_scan_token_here"

script:
  - ./travis-configure.sh
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then make && make test; fi

before_install:
  - ./travis-install.sh

addons:
  coverity_scan:
    project:
      name: "eclipse/mosquitto"
      description: "Build submitted via Travis CI"
    notification_email: roger@atchoo.org
    build_command_prepend: ./travis-configure.sh
    build_command: "make binary -j 4"
    branch_pattern: coverity-.*
