name: MQTT Library Build and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWITH_THREADING=no ..
          cmake --build . --config Release
          cd ..

      - name: Create Installer
        run: |
          cd installer
          "%PROGRAMFILES(x86)%\NSIS\makensis" mosquitto.nsi
        working-directory: installer

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: 'installer/mosquitto-*-install-windows-x86.exe'
