version: 1.0.{build}

image: Visual Studio 2019

environment:
  matrix:
    - NODE_VERSION: "20.x"

branches:
  only:
    - main

build_script:
  - ps: npm install
  - ps: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release -DWITH_THREADING=no ..
      cmake --build . --config Release
      cd ..

after_build:
  - ps: |
      cd installer
      "$env:ProgramFiles(x86)\NSIS\makensis" mosquitto.nsi
      cd ..

artifacts:
  - path: 'installer/mosquitto-*-install-windows-x86.exe'
    name: Installer
