name: Windows build

on:
  workflow_dispatch:
  push:
    branches: [ "master", "fixes" ]
    tags: [ "v[0-9]+.*" ]
  pull_request:
    branches: [ "master", "fixes" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  cjson:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          repository: DaveGamble/cJSON
          ref: v1.7.15

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure CMake cJSON
        run: cmake -B ${{github.workspace}}/build64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_CJSON_TEST=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_SHARED_AND_STATIC_LIBS=OFF -DCJSON_BUILD_SHARED_LIBS=OFF -DCJSON_OVERRIDE_BUILD_SHARED_LIBS=OFF -DCMAKE_GENERATOR_PLATFORM=x64

      # Add other steps for the cJSON job here

  mosquitto:
    runs-on: windows-2022
    needs:
      - cjson
    env:
      CJSON_DIR: C:\Program Files\cJSON

    steps:
      - uses: actions/checkout@v3
        with:
          repository: <YOUR_REPOSITORY>  # Replace <YOUR_REPOSITORY> with your actual repository

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Add other steps for the mosquitto job here
